name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      - name: Enable Web
        run: flutter config --enable-web
        
      - name: Clean
        run: flutter clean
        
      - name: Get dependencies
        run: flutter pub get
        
      - name: Verify directories
        run: ls -R
        
      - name: Build
        run: |
          flutter build web --release --base-href "/sudoku/"
          cp build/web/index.html build/web/404.html
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true 